#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

# Create config dir if not present
if [[ ! -d "${PWD}/config" ]]; then
    mkdir -p "${PWD}/config"
    hass --config "${PWD}/config" --script ensure_config
fi

# Symlink custom_components into config/ so HA discovers them natively
mkdir -p "${PWD}/config/custom_components"
if [[ ! -L "${PWD}/config/custom_components/ecocito" ]]; then
    ln -sf "${PWD}/custom_components/ecocito" "${PWD}/config/custom_components/ecocito"
fi

# Start Home Assistant
hass --config "${PWD}/config" --debug
